# Generated by Django 5.0.1 on 2024-01-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('team_city', models.CharField(max_length=40)),
                ('won', models.IntegerField()),
                ('points', models.FloatField()),
                ('established_date', models.DateField()),
            ],
        ),
    ]
