# Generated by Django 5.0.1 on 2024-02-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('task_number', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=20)),
                ('task_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
